channels:
- conda-forge
dependencies:
- python=3.9
- jupyter
- pyiron_base
- fenics =2019.1.0
- mshr =2019.1.0
- matplotlib
- seaborn
- pyiron-data=0.0.17
- pip
- pip:
  - git+https://github.com/pyiron/pyiron_base.git@master

# script.py and inputs.json nach conda_env/share/pyiron/templates/tensiletest
# pip install git+https://github.com/pyiron/pyiron_base@master

