# This workflow will install Python dependencies, run tests on pyiron template jobs

name: Test case pyiron script jobs

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install conda environment
      run: |
        ./make_environment.sh
    - name: Run test case
      run: |
        $CONDA/bin/python main.py