# This workflow will install Python dependencies, run tests on pyiron template jobs

name: Test case pyiron script jobs

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install conda environment
      run: |
        $CONDA/bin/conda env update --file ./environment.yml --name base
    - name: adding pyiron config file and pyiron resources dir
      run: |
        cp .ci_support/.pyiron $GITHUB_WORKSPACE/
        cp -r .ci_support/pyiron $GITHUB_WORKSPACE/
        echo $GITHUB_WORKSPACE
        ls -la $GITHUB_WORKSPACE/
    - name: Run test case
      run: |
        $CONDA/bin/python test_config.py