# This workflow will install Python dependencies, run tests on pyiron template jobs

name: Test case pyiron script jobs

on: [push]

jobs:
  test_pyiron:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.9"
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: environment.yml
    - name: adding pyiron config file and pyiron resources dir
      shell: bash -l {0}
      run: |
        echo $CONDA
        python .ci_support/pyiron_config.py
        ls -la
        pwd
    - name: Run test case
      shell: bash -l {0}
      run: |
        python main.py